#!/usr/bin/perl

$last="";

while (<STDIN>) {
    if ($_ =~ /^#/) {
        print;
    } else {
        $_ =~ /^(.+?)\t(.+?)\t(.+?)\t(.+?)\t(.+?)\t/;
        $chrom = $1;
        $pos = $2;
        $tag = $3;
        $ref = $4;
        $alt = $5;
	$curr = $chrom + "\tx" + $pos + "\t" + $ref + "\t" + $alt;
        if ($curr == $prev) {
            # remove anything which isn't biallelic
	} else {
            print;
        }
	$prev = $curr;
    }
}
