#!/usr/bin/env python
from __future__ import print_function
import sys

for line in sys.stdin:
    if line.startswith("#"):
        print(line.strip())
    else:
        fields = line.strip().split("\t")
        fields[2] = "."
        print("\t".join(fields))
