#!/bin/bash

if [ $# -ne 4 ];
then
echo usage: $0 '[ref_fasta] [base_vcf] [extension_vcf] [qual_info_name]'
echo overlays the files, using the QUAL and GT from the extension
exit
fi

ref=$1
base_vcf=$2
extend_vcf=$3
qual_info_name=$4

aux_vcf=$(basename $extend_vcf .vcf.gz).aug.vcf.gz
vcfqual2info $qual_info_name $extend_vcf \
    | vcfkeepinfo - $qual_info_name \
    | vcfkeepgeno - GT \
    | bgziptabix $aux_vcf

sort -r \
     <(zcat $base_vcf | head -1000 | grep "^#") \
     <(zcat $aux_vcf | head -1000 | grep "^#" | grep $qual_info_name )

vcfintersect -r $ref -u $base_vcf $aux_vcf \
    | vcfaddinfo - $aux_vcf \
    | vcfstreamsort -w 10000000000 \
    | vcfuniq \
    | grep -v "^#"

rm -f $aux_vcf
